/* TABLA PELICULAS */
CREATE TABLE PELICULAS (
    ID int NOT NULL,
    NOMBRE VARCHAR (30),
    GENERO VARCHAR (20),
    DURACION NUMBER (5),
    CONSTRAINT PK_PELICULAS PRIMARY KEY (ID)
);

/* TABLA SERIES */
CREATE TABLE SERIES (
    ID int NOT NULL,
    NOMBRE VARCHAR (30),
    GENERO VARCHAR (20),
    CONSTRAINT PK_SERIES PRIMARY KEY (ID)
);

/* DATOS PELICULAS */
INSERT INTO PELICULAS VALUES (1, "COCO", "ANIMACIÓN", "120");
INSERT INTO PELICULAS VALUES (2, "EL REY LEÓN", "ANIMACIÓN", "120");
INSERT INTO PELICULAS VALUES (3, "BUSCANDO A NEMO", "ANIMACIÓN", "120");
INSERT INTO PELICULAS VALUES (4, "HOTEL TRANSILVANIA", "ANIMACIÓN", "120");
INSERT INTO PELICULAS VALUES (5, "AMELIE", "ROMÁNTICA", "140");
INSERT INTO PELICULAS VALUES (6, "ANGELES Y DEMONIOS", "ACCIÓN", "150");

/* TABLA SERIES */

INSERT INTO PELICULAS VALUES (1, "STRANGER THINGS", "ACCIÓN", "40");
INSERT INTO PELICULAS VALUES (2, "BREAKING BAD", "ACCIÓN", "40");
INSERT INTO PELICULAS VALUES (3, "MR ROBOT", "ACCIÓN", "40");
INSERT INTO PELICULAS VALUES (4, "FRINGE", "ACCIÓN", "50");
INSERT INTO PELICULAS VALUES (5, "JUEGO DE TRONOS", "ACCIÓN", "50");
INSERT INTO PELICULAS VALUES (6, "DAWSON CRECK", "ROMÁNTICA", "45");
